### ISSUE TITLE
Merging our bb.js fork back to mothership

### ISSUE THREAD

**Issue by kachok** [blue-button/bluebutton.js#105]
We released version 1.0 of our Data Reconciliation Engine on May 31st (https://github.com/amida-tech/DRE)

As part of this product we forked and rebuilt bluebutton.js library (also incorporated most of Josh Mandel's code from ccda-to-json).

Here is repo with our fork - https://github.com/amida-tech/blue-button

Now, when there are no deadlines and time pressure, we want to merge our effort back to this project. How should we proceed with that?

**Comment by thetylerhayes** [comment]
@kachok You all ever get on a call?

Just re-visiting this because funny enough I just ran into the same issue you mentioned: C32 files using an `originalText` child element to contain the name of a medication, for example, rather than `displayName` attribute on the `code` tag:

```
// Pre-C32 CCDs put the problem name in this "originalText" field, and some vendors
// continue doing this with their C32, even though it's not technically correct
if (!name) {
  el = entry.template('2.16.840.1.113883.10.20.1.28').tag('originalText');
  name = el.val();
}
```

**Comment by sankarravi** [comment]
Going to close this but happy to reopen it if a conference call comes back in the plans @kachok ?
