### ISSUE TITLE
Checking for C32 vs. CCDA

### ISSUE THREAD

**Issue by thetylerhayes** [blue-button/bluebutton.js#116]
(I realize this is not an actual issue but just gonna put this here since I'm 99% sure no one checks [the Google Groups anymore](https://groups.google.com/forum/#!topic/bluebutton/bScIO4-5I7U) and I'm lost trying to figure this out.)

Right now this is the logic for choosing the C32 vs. CCDA parsers for a given document:

```
if (!data.template('2.16.840.1.113883.3.88.11.32.1').isEmpty()) {
	return 'c32';
} else if(!data.template('2.16.840.1.113883.10.20.22.1.1').isEmpty()) {
	return 'ccda';
}
```

I just downloaded one of my records from one of my providers and, lo and behold, it has *both* of these template codes.

Riddle me this:
1. Is the file wrong?
2. Or is bluebutton.js wrong? (If so it's probably my doing.) I.e., is it allowed per C32/CCDA spec to have both of these template codes? And if so, which standard is the file supposed to be considered: C32 or CCDA?

**Comment by sankarravi** [comment]
@thetylerhayes Did you run into any issues from this / have you seen more files like this? I'm curious whether the file in question had CCDA template type tags. I think we would probably parse the same way either way (use the CCDA parser for CDAs that are neither C32s or CCDAs), but we could change the document type to reflect that the file is actually an unknown type of CDA if it doesn't have any CCDA template tags.

**Comment by thetylerhayes** [comment]
Not that I can recall.
