### ISSUE TITLE
Push 0.2.1 to NPM

### ISSUE THREAD

**Issue by sankarravi** [blue-button/bluebutton.js#120]

**Comment by blacktm** [comment]
Sorry I missed this – just pushed. Also, is there a way to let others push to NPM?

**Comment by sankarravi** [comment]
@blacktm Yeah, it looks like you can add an owner via: https://docs.npmjs.com/cli/owner
My npm username is also sankarravi

**Comment by blacktm** [comment]
Cool, just added you.
