### ISSUE TITLE
'Cannot set property hl7Date of undefined' upon instantiation

### ISSUE THREAD

**Issue by thetylerhayes** [blue-button/bluebutton.js#121]
Every time I run `var BlueButton = require('bluebutton');` bb.js spits out this uncaught exception:

> TypeError: Cannot set property 'hl7Date' of undefined

When I comment out the Generators section this of course no longer blows up.

Anyone else seeing this? I've tried hunting down as much as I could on our end but not seeing anything so far so figured I'd mention it here.

NB: We just updated to latest version but were pretty out of date previously so I'm unsure when this would have started.

**Comment by sankarravi** [comment]
I think I fixed this in v0.2.1 (specifically in 7e693cc2142cffa05889005f607ec995c7e287a2), which Tom just pushed to NPM yesterday. Can you try grabbing 0.2.1 either from this repo or by downloading from NPM again and let me know if you're still seeing this?

**Comment by thetylerhayes** [comment]
I literally just downloaded from NPM for the first time 2 hours ago.

**Comment by sankarravi** [comment]
Ok, I'll give it a shot with a fresh set of dependencies then and see if there's something else I missed

**Comment by sankarravi** [comment]
Ah, ejs had a major version upgrade (1.0 -> 2.0) which changed their API. We should really update the package.json to actually specify versions :(

You should be able to fix this locally for now by either installing ejs 1.0.0 instead, or by just commenting out `ejs = require("ejs");` on L1302. I'll work on getting a proper fix out and getting it pushed to npm! Thanks for catching this.

**Comment by thetylerhayes** [comment]
:+1: :)

**Comment by sankarravi** [comment]
Fixed in 20a1e017af1845f9ad3a25cf0355dc95d60a1e3e, which I just pushed to NPM as 0.2.2
