### ISSUE TITLE
Change labs -> results in bluebuttonjs.com docs

### ISSUE THREAD

**Issue by thetylerhayes** [blue-button/bluebutton.js#122]
Where is the repo for bluebuttonjs.com located? I think I'm blind.

This: 

![screenshot 2015-01-08 19 12 45](https://cloud.githubusercontent.com/assets/344623/5675051/5b37b728-976a-11e4-956e-11b8a7402e2c.png)

**Comment by sankarravi** [comment]
It's a little bit of github black magic. You check out the `gh-pages` branch of the same repo and it magically turns into a different codebase / controls bluebuttonjs.com
