### ISSUE TITLE
Vital Signs - Template ID inconsistency

### ISSUE THREAD

**Issue by obalyuk87** [blue-button/bluebutton.js#125]
First of all, thank you all for supporting this great project! 

Seems like there is a possible bug with Vital Signs template id inconsistency between CCDA generation and CCDA parsing.

<h4>Problem Itself</h4>
If you generate a CCDA document using the bluebutton.js and then try to parse the generated xml file using bluebutton.js the vitals signs section gets lost. It is because the template id used in  generation of ccda document is different from template id used in parsing the CCDA document. 

Please refer to the lines below:
https://github.com/blue-button/bluebutton.js/blob/master/lib/documents/ccda.js#L91 (parsing)
https://github.com/blue-button/bluebutton.js/blob/master/lib/generators/ccda_template.ejs#L1461 (generating)

<h4>Solution I've Implemented</h4>
Meanwhile, for my needs I've added fallback condition, below.
```javascript
...
  case 'vitals':
        el = this.template('2.16.840.1.113883.10.20.22.2.4.1');
        //  if vitals were not found fallback to optional vitals
        if (el.entries == undefined){
            el = this.template('2.16.840.1.113883.10.20.22.2.4');
        }
        el.entries = entries;
        return el;
```

<h4>Background Info</h4>
source: http://www.cdatools.org/infocenter/index.jsp?topic=%2Forg.openhealthtools.mdht.uml.cda.consol.doc%2Fclasses%2FVitalSignsSection.html

According to the source above there are the two template ids for vital signs:
2.16.840.1.113883.10.20.22.2.4.1 and 2.16.840.1.113883.10.20.22.2.4  

http://cdatools.org/infocenter/index.jsp?topic=%2Forg.openhealthtools.mdht.uml.cda.mu2consol.doc%2Fclasses%2FSummaryOfCareRecord.html

Here is what it states:
```
SHALL have one Vital Signs Section with entries optional (TemplateID = 2.16.840.1.113883.10.20.22.2.4) 
or 
one Vital Signs Section with entries required (TemplateID = 2.16.840.1.113883.10.20.22.2.4.1)
```

**Comment by sankarravi** [comment]
This is a good catch, thanks. I will update this one and also look for other template IDs that we might be missing the optional version for

**Comment by sankarravi** [comment]
This also led me to write a test that takes the BB JSON, puts it through the generator, parses the resultant XML again and then compares the two pieces of JSON. I found loads of differences, some of which were just because the generator doesn't bother with some optional sections, but many of which were outright bugs or sections that were easy enough to add. Not sure how long it'll take me to finish up but the WIP is at https://github.com/blue-button/bluebutton.js/pull/127/
