### ISSUE TITLE
Question:  Usage with Meteor.js

### ISSUE THREAD

**Issue by frank1340** [blue-button/bluebutton.js#126]
Hello, 

Relative Javascript/Meteor neophyte.  How would I use this in Meteor.js?  Thank you.

**Comment by sankarravi** [comment]
I don't know very much about Meteor, but it looks like this is the recommended way to use standard NPM packages with Meteor: https://atmospherejs.com/meteorhacks/npm. So you would add that meteorhack, add bluebutton to your packages.json, and then use their special `Meteor.npmRequire` syntax to import the bluebutton package. Can't promise there won't be Meteor specific difficulties, but good luck!

**Comment by frank1340** [comment]
Ok.  That was my thought process too.  Thank you for the reply!
