### ISSUE TITLE
Include data in the Patient Instructions section in sandbox

### ISSUE THREAD

**Issue by thetylerhayes** [blue-button/bluebutton.js#128]
Anyone have a CCDA file we can model this off of? I've not seen this in the wild; curious to know what it looks like.

**Comment by thetylerhayes** [comment]
Oh here's a sample from the scorecard: https://github.com/chb/ccdaScorecard/blob/master/public/ccdaScorecard/example.ccda.xml#L638

Would still be interested in seeing what a fully robust sample looks like. That ^^ seems light.

**Comment by sankarravi** [comment]
@thetylerhayes There are some examples from Allscripts' submissions in the sample ccda repository:
https://github.com/jmandel/sample_ccdas/blob/master/Allscripts%20Samples/Enterprise%20EHR/b2%20Adam%20Everyman%20ToC.xml
[Check out https://github.com/alek-sys/sublimetext_indentxml to make that actually legible, if you use SublimeText]
That file is in our test suite so you can see how we parse it:
https://github.com/blue-button/bluebutton.js/blob/master/spec/javascripts/fixtures/json/allscripts_ccda_expected_output.json#L327

Or https://github.com/jmandel/sample_ccdas/blob/master/Allscripts%20Samples/Internal%20Test%20with%20MU%202%20data/170.314(e)(1)AMB_SummaryOfCareCED%20Type.xml#L1821

**Comment by thetylerhayes** [comment]
PR submitted. Question: should we update the instructions parser to look for a datetime too? I mentioned this in the PR too—I noticed cdatools has `<effectiveTime>` tags in their sample even though it's not explicitly required: http://cdatools.org/infocenter/index.jsp?topic=%2Forg.openhealthtools.mdht.uml.cda.consol.doc%2Fclasses%2FInstructionsSectionSample.html
