### ISSUE TITLE
Add 'translation' tag in 'results' parser

### ISSUE THREAD

**Issue by anmolagar** [blue-button/bluebutton.js#129]
I encountered a CCDA xml file which has translation in results

**Comment by anmolagar** [comment]
I wanted to contribute the code here, but i was not able to push the new branch i created. What process do you guys follow here.

**Comment by sankarravi** [comment]
Thanks, that would be appreciated! You can make a fork of the repository and then github will let you submit a pull request from your fork to the mainline. Here's a quick guide: https://guides.github.com/activities/forking/. Also instructions on running the tests after making your changes at http://www.bluebuttonjs.com/docs/#logistics-test

**Comment by anmolagar** [comment]
Thanks Ravi, I did the same. Please verify

**Comment by sankarravi** [comment]
I still had to fix all of the CCDA tests, but I made those adjustments and merged. Can you give me more details on the tests that were failing on master? I suspect you may not have run the `bower install` step (or if you ran it, that it didn't work), so some of the test CCDAs weren't available.
