### ISSUE TITLE
Test suite fails in timezone (-0400)

### ISSUE THREAD

**Issue by ufl-taeber** [blue-button/bluebutton.js#133]
Some of the tests fail when my timezone is set to _America/New\_York_.

**Steps to reproduce**

1. Set your timezone to _America/New\_York_. In Ubuntu 12.04, you can do this by:

        $ echo 'America/New_York' | sudo tee /etc/timezone
        $ sudo dpkg-reconfigure --frontend noninteractive tzdata

2. Run `grunt test` as [instructed](http://www.bluebuttonjs.com/docs/#logistics-test).

**What I expected**

All tests pass and a message like:

    Done, without errors.

**What I got**

3 errors. You can [see the full results on Travis](https://travis-ci.org/ufl-taeber/bluebutton.js/builds/55088324).

**More information**

It looks like there is a function in `lib/core.js` that is handling the formatting of dates. It uses `Date.getHour()` and other time methods to see if there is any time. Unfortunately, some of the times in the sample datasets are 4AM Zulu, which, in my time zone during Daylight Savings, is midnight. Therefore, instead of using the expected "datetime" format that is in the expected JSON-file output, the datetime is seen as lacking a time and is exported in the custom "date" format (MM/DD/YYYY) causing the tests to fail.

**Comment by sankarravi** [comment]
Good catch @ufl-taeber. I'm adding a flag to represent that a datetime was parsed with time-level precision, even if that time ended up being midnight, so the JSON formatter can still use the datetime format in this situation. Seems to enable the test pass to pass for arbitrary timezones on my machine. I hope to get Travis setup for the project sometime soon and we can run the tests in UTC to make sure we notice timezone issues in the future.

**Comment by ufl-taeber** [comment]
Thanks, @sankarravi! My Travis build is now passing. 

Travis is pretty straightforward to setup. You basically just log in with your GitHub account, enable Travis to build for a particular repository, and then add a configuration file. You can even use my [`.travis.yml`](https://github.com/ufl-taeber/bluebutton.js/blob/master/.travis.yml) file if you'd like:

```yaml
language: node_js
node_js:
    - "0.12"
before_script:
    - npm install -g grunt-cli
    - bower install
    - echo 'America/New_York' | sudo tee /etc/timezone
    - sudo dpkg-reconfigure --frontend noninteractive tzdata
```

**Comment by sankarravi** [comment]
@blacktm can you give me admin privileges on the project so I can grant Travis permission to access the repository?

**Comment by blacktm** [comment]
@sankarravi Just bumped the permissions. Let me know if it didn't work.

**Comment by sankarravi** [comment]
Sweet, it's set up!
