### ISSUE TITLE
Patient Address - Street/Apt

### ISSUE THREAD

**Issue by Smcner** [blue-button/bluebutton.js#146]
I've noticed that there is only one line for patient street address, but often people in urban areas have two address lines or a street address separated by a comma (123 Test Lane, Apt G2). But after parsing the xml into JSON and calling the objects, there is no space, comma, etc, between the last letter of the street address and the first letter/number of the apartment (123 Test LaneAptG2).

Is this an issue with how I am parsing the JSON objects or is it an issue with the js?

**Comment by sankarravi** [comment]
As always, a sample file that reproduces the issue is helpful (really a prerequisite to check it out). Even if it's a specific one of the files you've already referenced.

**Comment by Smcner** [comment]
It's all of the referenced CDAs in #140 - victoriatest, seantest, brucewayne - found in my master. Seems that the demographics parser just needs to add a space or include the comma. It's safe to assume that any of the addresses in the document output have the same issues (FYI, most EHRs list the provider in "documentation_of" and not author)...

**Comment by sankarravi** [comment]
If you look at the JSON for VictoriaTest:

```
{ street: [ '1234 100TH ST', 'APT 21' ],
  city: 'FOREST TREES',
  state: 'NY',
  zip: '11375',
  country: 'USA' }
```

You'll see that the street address is an Array. Every `<streetAddressLine>` in the source file turns into an entry in the array. So probably wherever you are consuming the JSON is converting the Array to a String by just concatenating all of the entries.

**Comment by Smcner** [comment]
Ah, got it. Thanks!
