### ISSUE TITLE
Past Medical History - "History of Past Illness"

### ISSUE THREAD

**Issue by Smcner** [blue-button/bluebutton.js#147]
I've noticed that one field not recognized by BB is past medical history. This is very different than Problems in that problems or "problem lists" look at chronic often active conditions while Medical History may be a condition suffered in the past or is resolved but is pertinent to that patient's history and is important to track in case of renewed symptoms or complications due to that condition.

One example is brucewayne - in my CDA master. Medical history can be found under code "11348-0" and displayName "History or Past Illness". But, oddly, the actually structured coding can be found under code "55607006" and displayName "problem" (still not recognized by BB) - there is both a referenced text and a coded displayName within this field "No pertinent past medical history"

**Comment by sankarravi** [comment]
Yeah, there many more sections supported by the spec than BB currently supports (there are 60+ total). The sections that are supported mostly grew out of what library users found themselves needing.

Hopefully you'll find that the existing infrastructure makes it relatively straightforward to support the History of Past Illness section. You'll need to edit documents/ccda.js and c32.js to add the template IDs for the section in question, parsers/ccda.js and c32.js to add your new data to the JSON, create new files like history_of_illnesses.js to parse the data you care about from your section, and add your new file to the Gruntfile, so it gets included in the final build.

If you want to submit the change as PR to the main project, you'll also need to update the tests to make sure they're passing. The last section we added was smoking_status, which was part of 1249112309d960357e745e30f67e193a629455e6 for reference.

**Comment by Smcner** [comment]
Great - I'll give it a go and see what I can do. I'm no seasoned developer, by any means, but I can probably figure it out by looking at what's already been done. Thanks!

**Comment by sankarravi** [comment]
@Smcner How did your efforts / your broader presentation go?

**Comment by Smcner** [comment]
Hey - sorry, went radio silent with some transitions and piled on crap at work. Haven't been able to test it in a couple months and working for public health, things are slow...haha. Dust is settling so I'll be going back into it shortly but I'll close this out and let you know if I find issues when I get going again
