### ISSUE TITLE
Encounter Provider

### ISSUE THREAD

**Issue by Smcner** [blue-button/bluebutton.js#148]
I've noticed when pulling the encounter info from BB JSON that it's not capturing the "performer" or provider who rendered the care for that visit. Oddly enough, this can be seen in the example CDA seen on the bluebuttonjs.com page - the performer is referenced in the html table within the encounters component and is "Dr. Henry Seven".

The issue can also be noticed in a new example CDA sent by EPIC - https://github.com/Smcner/CCDA/blob/master/chrisavery.xml - except in this case the provider is listed under the assignedPerson tag then name with given and family tags. In this example the provider is "John D. Stadler".

**Comment by sankarravi** [comment]
The CDA spec is so complex :)

Yeah, looks like we don't do a very good job parsing the encounter performer/participant. Will try to take a look at that
