### ISSUE TITLE
Procedure Specimen always null

### ISSUE THREAD

**Issue by norlowski** [blue-button/bluebutton.js#149]
in bluebutton.js/lib/parsers/ccda/procedures.js:

    // 'specimen' tag not always present
    // el = entry.tag('specimen').tag('code');
    // var specimen_name = el.attr('displayName'),
    //     specimen_code = el.attr('code'),
    //     specimen_code_system = el.attr('codeSystem');
    var specimen_name = null,
        specimen_code = null,
        specimen_code_system = null;

There are `<specimen>` in some of the sample CCDAs. Are these not required to match the NIST tool?

**Comment by sankarravi** [comment]
@norlowski Sorry I've neglected the issues for a bit.

There are loads of data elements that the library doesn't parse. Specimen is definitely an optional field, and there's hardly even detail on in the specification document on the tag (there's basically just a single code sample that has a specimen in it). But that comment ("not always present") doesn't make much sense to me though – I don't know why the tag not always being present would be any reason to never try to parse it. So I don't see any harm to reverting to the commented out version which parses the field if available.
