### ISSUE TITLE
Relies on <?xml to choose parser

### ISSUE THREAD

**Issue by glow-mdsol** [blue-button/bluebutton.js#150]
Hi

I don't believe the xml declaration is required by the CDA guide and some sample CDAs don't include it (eg sample_ccdas/Partners HealthCare/partners.ccda.xml).  If the choices are XML or JSON can we just search for a leading `<` in `bluebutton.js` (line 28) before switching to the JSON parser?  We should wrap the XML parser looking for exceptions as well and assure ourselves that the root node is a `ClinicalDocument` after parsing.

The following files in the sample_ccdas repo don't have the xml declarations:
![image](https://cloud.githubusercontent.com/assets/1116105/9546345/d1f559f8-4d89-11e5-82c6-a99cd75eee01.png)

I'm not suggesting we reinforce bad behaviour, just make sure we can deal with it appropriately when it comes in.

**Comment by sankarravi** [comment]
@glow-mdsol This is a fair point. We've definitely run into this problem with real world files and we hacked around it by detecting the situation and inserting a proper XML header upstream of BB.js... but there's no reason the library shouldn't handle this case. Fixing.
