### ISSUE TITLE
insurance

### ISSUE THREAD

**Issue by chacliff** [blue-button/bluebutton.js#152]
is there an insurance section in CCDA's my coworker believes it to be under the "Payers". the title being Insurance Providers.

**Comment by sankarravi** [comment]
From a quick look, it does look like the CCDA spec supports an optional Payers section to hold insurance info. The CCDA spec is huge and the BB JS library has evolved to parse/generate sections that various users have had a need for (in large part, the parts required by meaningful use), so there are many spec-ed sections that we don't have support for (yet – always open to pull requests). Are you running into files in the wild with this section or looking to generate CCDAs containing it?

**Comment by chacliff** [comment]
my company needs to include insurance information and that seems to be the section they will be including, my boss has a running server of this and may be adding the section but i'm sure he will do a pull request once he completes the section. At the very least he will provide a starting point for you on the section. 
note: my coworker kept refering to it as payers and claimed it was part of the CCDA spec. i'll provide any info i can asap
