### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by SDSilicus** [blue-button/bluebutton.js#155]
![image](https://cloud.githubusercontent.com/assets/13151580/11182253/4eaddc6a-8c8f-11e5-8b66-09a480cdd766.png)

I am using below code to create ccd document having above error.  
It seems var end = str.indexOf(close, i); in ejs.js file is causing this error where str is Buffer Object and indexOf is not supported method for the object. Any assistance.

var fs = require('fs');
var BlueButton = require('bluebutton');
var	path = require('path');
var xml = fs.readFileSync('./BlueButton.xml', 'utf-8');
var myRecordJson = BlueButton(xml); // open file and get json document

var template = fs.readFileSync('./node_modules/bluebutton/build/ccda_template.ejs');
var myRecord12 = BlueButton(myRecordJson.data.json(), {
  generatorType: 'ccda',
  template: template
});

**Comment by sankarravi** [comment]
@SDSilicus Looks like the bug is with:
`var template = fs.readFileSync('./node_modules/bluebutton/build/ccda_template.ejs');`

That should be:
`var template = fs.readFileSync('./node_modules/bluebutton/build/ccda_template.ejs', 'utf-8');`

Otherwise, the template is a Buffer object, which can't be fed into EJS. I'll update the docs and look at making that error more obvious.

**Comment by SDSilicus** [comment]
Yes using UTF-8 has worked. Thank you

If not already done will send you pull request after changing documentation.

Sent from my iPhone

On 18 Nov 2015, at 07:52, "Ravi Sankar" <notifications@github.com<mailto:notifications@github.com>> wrote:


@SDSilicus<https://github.com/SDSilicus> Looks like the bug is with:
var template = fs.readFileSync('./node_modules/bluebutton/build/ccda_template.ejs');

That should be:
var template = fs.readFileSync('./node_modules/bluebutton/build/ccda_template.ejs', 'utf-8');

Otherwise, the template is a Buffer object, which can't be fed into EJS. I'll update the docs and look at making that error more obvious.

-
Reply to this email directly or view it on GitHub<https://github.com/blue-button/bluebutton.js/issues/155#issuecomment-157576042>.

The information in this email is confidential and may be legally privileged. It is intended solely for the addressee and access to it by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken based on it, is strictly prohibited and may be unlawful.
