### ISSUE TITLE
Seeing sample CCDA observation not picking up text

### ISSUE THREAD

**Issue by talvola** [blue-button/bluebutton.js#158]
This may be a case of bad data - apologize if so.

https://raw.githubusercontent.com/chb/sample_ccdas/master/Cerner%20Samples/Transition_of_Care_Referral_Summary.xml

contains a sample C-CDA record (from the nice sample_ccdas repository).

The fragment of XML in it for blood pressure:

								<observation classCode="OBS" moodCode="EVN">
									<templateId root="2.16.840.1.113883.10.20.22.4.27"/>
									<id root="32FE5620-BCED-4B41-88F2-E0D92D6F2C28"/>
									<code nullFlavor="UNK">
										<originalText>Mean Arterial Pressure</originalText>
									</code>
									<text>
										<reference value="#VSEVN17364884"/>
									</text>
									<statusCode code="completed"/>
									<effectiveTime value="20130710220000.000-0500"/>
									<value xsi:type="PQ" value="113" unit="mm[Hg]"/>
									<interpretationCode nullFlavor="UNK">
										<originalText>Extreme High</originalText>
									</interpretationCode>
									<author>
										<time value="20130710220147.000-0500"/>
										<assignedAuthor classCode="ASSIGNED">
											<id nullFlavor="NI"/>
											<addr nullFlavor="UNK"/>
											<assignedPerson>
												<name>
													<given nullFlavor="NA"/>
													<family nullFlavor="NA"/>
												</name>
											</assignedPerson>
										</assignedAuthor>
									</author>
									<referenceRange typeCode="REFV">
										<observationRange>
											<text>70-100 mmHg</text>
										</observationRange>
									</referenceRange>
								</observation>
							</component>

gets translated into this:

            {
                "identifiers": [
                    {
                        "identifier": "32FE5620-BCED-4B41-88F2-E0D92D6F2C28"
                    }
                ],
                "status": "completed",
                "date_time": {
                    "point": {
                        "date": "2013-07-11T03:00:00.000Z",
                        "precision": "subsecond"
                    }
                },
                "value": 113,
                "unit": "mm[Hg]"
            },

notice that the text "Mean Arterial Pressure" is not present in the JSON.    Is this something that feels like valid syntax in the C-CDA that should be handled by the toolkit?

Just eyeballing - not sure if the reference range is that interesting, but it isn't being carried over either.

**Comment by sankarravi** [comment]
Based on the JSON in your sample, I'm pretty sure you're using the Amida Tech fork of the library (https://github.com/amida-tech/blue-button), so you probably want to open an issue over there

**Comment by talvola** [comment]
I wasn't even aware of the fork - thanks for the note.   Just beginning my understanding of what tools are out there.

**Comment by sankarravi** [comment]
No problem!
