### ISSUE TITLE
Not all of a procedures's participants are "device"s.

### ISSUE THREAD

**Issue by jmandel** [blue-button/bluebutton.js#17]
For example the following is silly:

```
    "device": {
      "name": "General Acute Care Hospital",
      "code": "GACH",
      "code_system": "2.16.840.1.113883.5.111"
    }
```

The hospital isn't listed as a device; it's listed as Service Delivery Location (`templateId = 2.16.840.1.113883.10.20.22.4.32`).  You'll want to identify devices by `[@templateId = '2.16.840.1.113883.10.20.22.4.37']/../playingDevice/code...`

(This appears to stem from the use of `getElementsByTag` at https://github.com/blue-button/bluebutton.js/blob/master/src/core.js#L45, which recurses and finds nested elements, not just direct-children -- which can make the convenience wrappers fail in surprising ways when it doesn't find what it expects at the top of the hierarchy.)

**Comment by thetylerhayes** [comment]
FWIW we already do something similar to this in the C32 results parser: https://github.com/blue-button/bluebutton.js/blob/master/lib/parsers/c32/results.js#L36:

```
... 
// sometimes results organizers contain non-results. we only want tests
    if (observation.template('2.16.840.1.113883.10.20.1.31').val()) {
        var date = parseDate(observation.tag('effectiveTime').attr('value'));
...
```

So some sorta kinda precedent exists.

**Comment by sankarravi** [comment]
Yep, I have a fix for this on https://github.com/blue-button/bluebutton.js/pull/127/files#diff-e8efe13f6db4f401b317888b6d6cc9f4R39. Working on getting that PR ready for merge.

**Comment by norlowski** [comment]
Was this merged into master? I still see the above code with "participant => device".

Is the example @jmandel mentioned just a data problem in the *official* example ccda?

**Comment by sankarravi** [comment]
@norlowski The code on master looks like this:
```
    // participant => device
    el = entry.template('2.16.840.1.113883.10.20.22.4.37').tag('code');
    var device_name = el.attr('displayName'),
        device_code = el.attr('code'),
        device_code_system = el.attr('codeSystem');
```
So it now looks specifically for a tag that identifies a device. This should mean that only actual devices get parsed as devices. You can see in https://github.com/blue-button/bluebutton.js/commit/79042f596a512e0c590b50ea3af420762cc43aad#diff-46f39fe99505a71da1d296e1f8f3969eR640 that Josh's specific example is no longer parsed as a device (or technically that the tests, which pass, had to adjust for that expectation)

**Comment by norlowski** [comment]
Thanks for the updates!
