### ISSUE TITLE
Capture missing data

### ISSUE THREAD

**Issue by blacktm** [blue-button/bluebutton.js#70]
- [ ] NPI numbers, look for `<id root="2.16.840.1.113883.4.6"/>`
- [ ] URLs for code systems, see #5
- [x] Date document was produced (effective date?)
- [x] Creator of the document (provider, organization)
- [ ] Document timespan (earliest item, latest item)
- [ ] Encounters need a start and end date (especially inpatient encounters)
- [ ] Allergy and Immunization "given", "not given" status. See #14 and #7
- [ ] Review sample CCDAs from EMERGE for other missing data: http://onc-emerge.org/

**Comment by sankarravi** [comment]
Going to close this – the community can request any fields that are affecting them

**Comment by blacktm** [comment]
Sounds like a more manageable approach. Thanks.
