### ISSUE TITLE
Include C32 procedures from Results sections

### ISSUE THREAD

**Issue by thetylerhayes** [blue-button/bluebutton.js#73]
Per https://github.com/blue-button/bluebutton.js/pull/72#issuecomment-26114114

**Comment by sankarravi** [comment]
@thetylerhayes Have you guys done this on your fork / is it still useful / can we close it?

**Comment by thetylerhayes** [comment]
We haven't. Probably still useful though. My biggest question is whether or not procedures included in results sections are doubled-up from the procedures section. If they are, we don't want to dual import. I'll try to find a C32 sample file that has these and suss it out.

**Comment by thetylerhayes** [comment]
OK so I took a look at some C32 files. Sure enough some had procedures inside results. Typically it'd be structured something like this:

```
<entry>
    <organizer>
        <templateId root="2.16.840.1.113883.10.20.1.32"/>
        <code code="12345" codeSystem="1.23.4567.89.0" codeSystemName="LOINC" displayName="SOME LAB TEST PANEL NAME"/>
        <effectiveTime value="19760101010000"/>
        <component>
            <observation ... > <!-- a.k.a. test result -->
                <templateId root="2.16.840.1.113883.10.20.1.31"/>
            </observation>
        </component>
        <component>
            <observation ... > <!-- a.k.a. test result -->
                <templateId root="2.16.840.1.113883.10.20.1.31"/>
            </observation>
        </component>
        <component>
            <observation ... > <!-- a.k.a. test result -->
                <templateId root="2.16.840.1.113883.10.20.1.31"/>
            </observation>
        </component>
        <component>
            <procedure ... > <!-- a.k.a. procedure -->
                <templateId root="2.16.840.1.113883.10.20.1.29"/>
                <code code="12345" codeSystem="1.23.4567.89.0" codeSystemName="LOINC" displayName="SOME LAB TEST PANEL NAME"/> <!-- exact same as overall panel name (<code> tag) above -->
            </procedure>
        </component>
    </organizer>
</entry>
```

In other words: a results element would parent a bunch of test results (`<observation>` tags) and *also* one `<procedure>`. And the procedure would have the same details as the parenting results element itself. Which makes sense.

Never found a situation where there would be a procedure inside a results element that *also* was its own procedure in the Procedures section. I'm sure some C32 file somewhere has that situation but I don't think it's a thing to worry about. Pull request incoming.

**Comment by sankarravi** [comment]
Decided to leave this alone based on the discussion in #137
