### ISSUE TITLE
Breaking bluebutton.js into single use modules

### ISSUE THREAD

**Issue by robdodson** [blue-button/bluebutton.js#79]
What do you guys think about taking the current implementation of bluebutton.js and breaking it down into smaller modules that can be composed together? Right now it's tricky to test bluebutton.js and if you add something to it, then all developers must now accept that feature, even if it's something they don't want.

It seems like because medical records are so complex, and there are a number of different styles of XML (CCDA, C32, etc?), that it might make more sense to build a chain of modules instead of having one big library. Just looking at the current implementation I think `xml.js` could be its own module, `codes.js` could be its own module, the `ccda/` dir could be one and the `c32/` dir could be one.

I guess in my mind, an almost ideal scenario might look a little like how the Connect framework deals with http requests. In Connect a request comes in and then it's acted upon by ["middleware".](http://www.senchalabs.org/connect/) Typically middleware is an npm module that exports a single function that just does something to the request or response object. For instance, adding something to the session or gzipping an asset, etc. You can chain middleware together (that's the point) and do really powerful stuff out of simple pieces.

`http request -> logger -> basicAuth -> gzip -> response sent`

I'm wondering if you could do something similar when working with bluebutton. Even if it's not the exact same paradigm, I think breaking the library down into smaller pieces will make it easier to test and will encourage more people to submit pull requests because they'll be more comfortable working on a tiny piece of code instead of the entire library.

Thoughts?

@jmandel @blacktm @mjacksonw @thetylerhayes

**Comment by sankarravi** [comment]
Going to close this since I don't think we'll be taking any action on it in the near future
