### ISSUE TITLE
Add/refactor method of detecting data format without parsing it into JSON

### ISSUE THREAD

**Issue by kachok** [blue-button/bluebutton.js#80]
e.g. just get type CCDA or C32 for input data without complete parsing

**Comment by sankarravi** [comment]
> without complete parsing
Is the goal to be able to detect the format quickly for a large number of files? Or is it to reduce the number of lines required to do format dection? Or something else? Trying to understand more about why avoiding JSON parsing might be a goal / whether this is still relevant.
