### ISSUE TITLE
Add info about CCDA template into document metadata

### ISSUE THREAD

**Issue by kachok** [blue-button/bluebutton.js#81]
Right now data.document contains only type, add template used (Continuity of Care, etc. see http://ccda.sitenv.org/C-CDA#See also-Document-Level Templates)

**Comment by thetylerhayes** [comment]
Not sure if it got removed, but I don't even see document type in `data.document` now: https://github.com/blue-button/bluebutton.js/blob/master/lib/parsers/ccda/document.js

+1 to response including whether a doc is C32 vs. CCDA at the very least

**Comment by sankarravi** [comment]
C32 vs. CCDA got moved into a key above `data` (a peer of `data`) called `type`:
http://www.bluebuttonjs.com/docs/#parsing-overview

(I don't have a strong opinion on keeping it out of `data.document` or anything though, so if there's a reason it's helpful to get into there, that seems fine with me)
