### ISSUE TITLE
Document Models

### ISSUE THREAD

**Issue by mmccall** [blue-button/bluebutton.js#98]
Hi All;

While Dmitry has been benchmarking, I've been taking a look at the models.  I think it's a good exercise to review what is coming out of bb.js and document it to make sure it isn't missing anything/erroneous.  As a first pass, I used github's wiki to build a mongoose-like JSON schema on demographics, and found a few things.  Would love some feedback.  Eventually, something like this would be nice to have for all sections I think.

https://github.com/amida-tech/bluebutton.js/wiki/Demographics

**Comment by sankarravi** [comment]
Linking this to #105 and closing it as an independent entity
